// frontend/src/components/grid.tsx
import type { CSSProperties, ReactNode } from "react";

type GridProps = {
    gap?: number | string;
    className?: string;
    style?: CSSProperties;
    children: ReactNode;
} & (
    | { rows: string; columns?: never }
    | { rows?: never; columns: string });

export default function Grid({
    rows,
    columns,
    gap,
    className,
    style,
    children,
}: GridProps) {
    const gridStyle: CSSProperties = {
        display: "grid",
        // The defined axis uses the provided track list; the cross axis fills all space.
        gridTemplateRows: rows ?? "1fr",
        gridTemplateColumns: columns ?? "1fr",
        ...style,
    };

    return (
        <div className={`gap-${gap} ${className}`} style={gridStyle}>
            {children}
        </div>
    );
};

// frontend/src/components/Grid.svelte
<script lang="ts">
    import type { Snippet } from "svelte";

    type Props = {
        gap?: number | string;
        class?: string;
        style?: string;
        children: Snippet;
    } & (
        | { rows: string; columns?: never }
        | { rows?: never; columns: string });

    let {
        rows,
        columns,
        gap,
        class: className = "",
        style = "",
        children,
    }: Props = $props();

    /// The defined axis uses the provided track list; the cross axis fills all space.
    let inlineStyle = $derived(
        `display:grid;`
        + `grid-template-rows:${rows ?? "1fr"};`
        + `grid-template-columns:${columns ?? "1fr"};`
        + style);
</script>

<div class="grid gap-{gap} {className}" style={inlineStyle}>
    {@render children()}
</div>
